<a href="https://colab.research.google.com/github/NguyenDuyTan0302/BaiTapNNLT/blob/master/bai_tap_kiem_dinh_z_t.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

XÂY DỰNG CHƯƠNG TRÌNH KIỂM ĐỊNH Z (HOẶC T) CHO CÁC BÀI TẬP SAU

Gợi ý:

- Số liệu được sinh ngẫu nhiên theo phân phối chuẩn
- Sử dụng gói phần mềm statsmodels để tiến hành kiểm định
- Đối với các bài tập kiểm định giả thuyết thì sinh viên cần phát biểu các giả thuyết (bằng tiếng Việt) $H_{0}$ và $H_{a}$ trước khi lập trình kiểm định

In [63]:
from scipy import stats
import numpy as np
import math
from statsmodels.stats.weightstats import ztest

Bài 1: You’re a Q/C inspector for Gallo. The sample standard deviation for 2-liter bottles is .05 liters.  A random sample of 100 bottles showed sasmple mean = 1.99 liters.  What is the 90%  confidence interval estimate of the true mean amount in 2-liter bottles? 

In [2]:
mean = 1.99
std = 0.05
err = std / (math.sqrt(std))
stats.norm.interval(alpha= 0.90, loc = mean, scale = err)

(1.6221995477099427, 2.357800452290057)

Bài 2: You’re a time study analyst in manufacturing.  You’ve recorded the following task times (min.): 3.6, 4.2, 4.0, 3.5, 3.8, 3.1. What is the 90% confidence interval estimate of the population mean task time? 

In [3]:
data = [3.6, 4.2, 4, 3.5, 3.8, 3.1]
N = 6
mean = np.mean(data)
err = stats.sem(data)
stats.t.interval(alpha = 0.90,df = N - 1, loc =mean, scale = err)

(3.3792758632100677, 4.020724136789934)

Bài 3: Does an average box of cereal contain 368 grams of cereal?  A random sample of 25 boxes had $\overline{\rm x}$ = 372.5.  The company has specified $\sigma$ to be 25 grams.  Test at the .05 level of significance.

Giả thuyết gốc: "Trung bình 1 hộp ngũ cốc có chứa 368grams ngũ cốc"

Giả thuyết thay thế: "Trung bình 1 hộp ngũ cốc không chứa 368grams ngũ cốc"

Xây dựng giả thuyết:
$$H_0: μ = 368$$

Giả thuyết thay thế:

$$H_a: μ \ne 368$$

Với:
- $α = 0.05$

In [16]:
# Sinh mẫu ngẫu nhiên với cỡ mẫu 25, trung bình 372.5, độ lệch chuẩn 25
sample = np.random.normal(loc = 372.5, scale = 25, size = 25)
sample

array([381.44170419, 400.61907457, 359.06463729, 406.19673271,
       367.54060683, 347.366475  , 404.63917283, 397.60835668,
       378.23606641, 381.60967923, 384.20560747, 393.13152837,
       335.9023904 , 385.61272317, 370.02149108, 405.52778804,
       363.20045198, 391.04876241, 425.67628263, 368.79386049,
       381.2864541 , 402.35028785, 385.53095905, 376.15833007,
       384.9379868 ])

In [15]:
# Xác định các thông số:
null_mean = 368
alpha = 0.05

In [17]:
#Kiểm định t
t_statistic, p_value = stats.ttest_1samp(sample, null_mean)
print("Giá trị p là:", p_value)
if(p_value <  alpha):
  print("Có bằng chứng để bác bỏ giả thuyết H0")
else:
  print("Chưa có bằng chứng để bác bỏ giả thuyết H0")

Giá trị p là: 0.0009046082608881457
Có bằng chứng để bác bỏ giả thuyết H0


Bài 4: You’re a Q/C inspector.  You want to find out if a new machine is making electrical cords to customer specification: average breaking strength of 70 lb. with $\sigma$ = 3.5 lb.  You take a sample of 36 cords & compute a sample mean of 69.7 lb.  At the .05 level of significance, is there evidence that the machine is not meeting the average breaking strength?

Giả thuyết gốc: "Máy được làm theo yêu cầu của khách hàng"

Giả thuyết thay thế: "Máy không được làm theo yêu cầu của khách hàng"

Xây dựng giả thuyết:
$$H_0: μ = 70$$

Giả thuyết thay thế:

$$H_a: μ \ne 70$$

Với:
- $α = 0.05$

In [13]:
# Sinh mẫu ngẫu nhiên với cỡ mẫu 36, trung bình 69.7, độ lệch chuẩn 3.5
sample = np.random.normal(loc = 69.7, scale = 3.5, size = 36)
sample

array([67.76537989, 66.77618137, 69.91412519, 71.70393903, 72.00036999,
       68.42351863, 63.08832121, 66.60382019, 69.72906239, 68.78992769,
       66.93172989, 74.71715213, 68.84724411, 64.8371976 , 72.78678962,
       64.98088778, 75.41196635, 67.54510501, 71.8811628 , 72.38027964,
       74.88350204, 68.75637326, 61.85467013, 69.06135023, 71.62813493,
       67.89190688, 70.83139233, 68.80984024, 68.87189515, 65.49980911,
       67.92897534, 70.96199223, 75.93601255, 68.80176702, 68.50085938,
       69.10467978])

In [12]:
# Xác định các thông số:
null_mean = 70
alpha = 0.05

In [26]:
# Kiểm định z:
ztest_Score, p_value= ztest(sample, value = null_mean, alternative='two-sided')
print("Giá trị của p là:",p_value)
if(p_value <  alpha):
  print("Có bằng chứng để bác bỏ giả thuyết H0")
else:
  print("Chưa có bằng chứng để bác bỏ giả thuyết H0")

Giá trị của p là: 0.11078434616744147
Chưa có bằng chứng để bác bỏ giả thuyết H0


Bài 5: Does an average box of cereal contain more than 368 grams of cereal?  A random sample of 25 boxes showed $\overline{\rm x}$ =  372.5.  The company has specified $\sigma$ to be 25 grams.  Test at the .05 level of significance.

Giả thuyết gốc: "Trung bình 1 hộp ngũ cốc có chứa 368grams ngũ cốc"

Giả thuyết thay thế: "Trung bình 1 hộp ngũ cốc chứa nhiều hơn 368grams ngũ cốc"

Xây dựng giả thuyết:
$$H_0: μ = 368$$

Giả thuyết thay thế:

$$H_a: μ > 368$$

Với:
- $α = 0.05$

In [23]:
# Sinh mẫu ngẫu nhiên với cỡ mẫu 25, trung bình 372.5, độ lệch chuẩn 25
sample = np.random.normal(loc = 372.5, scale = 25, size = 25)
sample

array([385.61920764, 381.66134411, 365.79664795, 395.82306867,
       419.05666785, 377.50080043, 340.25724121, 384.98743323,
       400.74464318, 365.52505963, 387.68418298, 355.81404701,
       386.11762788, 384.71652347, 365.92924568, 352.68767134,
       397.13497958, 340.53331502, 361.11384926, 364.78881095,
       329.38194915, 370.42226881, 413.64324224, 370.77076072,
       377.61452967])

In [24]:
# Xác định các thông số:
null_mean = 368
alpha = 0.05

In [25]:
#Kiểm định t
t_statistic, p_value = stats.ttest_1samp(sample, null_mean)
print("Giá trị p là:", p_value)
if(p_value <  alpha):
  print("Có bằng chứng để bác bỏ giả thuyết H0")
else:
  print("Chưa có bằng chứng để bác bỏ giả thuyết H0")

Giá trị p là: 0.12387008600571708
Chưa có bằng chứng để bác bỏ giả thuyết H0


Bài 6: You’re an analyst for Ford.  You want to find out if the average miles per gallon of Escorts is at least 32 mpg. Similar models have a standard deviation of 3.8 mpg. You take a sample of 60 Escorts & compute a sample mean of 30.7 mpg. At the .01 level of significance, is there evidence that the miles per gallon is less than 32?

Giả thuyết gốc: "Số dặm trên một gallon của Escort bằng 32 mpg"

Giả thuyết thay thế: "Số dặm trên một gallon của Escortbé hơn 32 mpg"

Xây dựng giả thuyết:
$$H_0: μ = 32$$

Giả thuyết thay thế:

$$H_a: μ < 32$$

Với:
- $α = 0.01$

In [31]:
# Sinh mẫu ngẫu nhiên với cỡ mẫu 60, trung bình 30.7, độ lệch chuẩn 3.8
sample = np.random.normal(loc = 30.7, scale = 3.8, size = 60)
sample

array([27.37975051, 27.40117395, 25.86724195, 28.08674717, 33.44620037,
       31.09646772, 28.85621799, 25.89824277, 32.57114966, 32.04834618,
       29.32396573, 24.52363377, 27.4184719 , 29.47233341, 27.89152408,
       30.79125612, 29.42002788, 31.17919402, 34.3696253 , 28.22732248,
       32.66354814, 32.8951108 , 28.43865025, 34.67955348, 32.0356723 ,
       34.7228972 , 30.59837633, 29.59236224, 30.22122514, 31.71237359,
       28.50435882, 28.96360159, 34.70667543, 28.91733413, 25.47567054,
       35.92635816, 26.02621424, 33.31745539, 29.39225712, 30.47549875,
       26.39218391, 24.58310913, 24.16639106, 34.93370842, 26.11187795,
       30.75861289, 27.51222242, 29.92503079, 33.74108148, 31.30173956,
       29.28109622, 25.10908755, 24.6944833 , 27.62504782, 32.84805885,
       33.00414915, 31.23335307, 29.2395686 , 34.00665935, 28.14820371])

In [30]:
# Xác định các thông số:
null_mean = 32
alpha = 0.01

In [32]:
# Kiểm định z:
ztest_Score, p_value= ztest(sample, value = null_mean, alternative='smaller')
print("Giá trị của p là:",p_value)
if(p_value <  alpha):
  print("Có bằng chứng để bác bỏ giả thuyết H0")
else:
  print("Chưa có bằng chứng để bác bỏ giả thuyết H0")

Giá trị của p là: 1.8414773646721028e-08
Có bằng chứng để bác bỏ giả thuyết H0


Bài 7: Does an average box of cereal contain 368 grams of cereal?  A random sample of 25 boxes showed $\overline{\rm x}$ = 372.5.  The company has specified $\sigma$ to be 15 grams.  Find the p-Value.

Giả thuyết gốc: "Trung bình 1 hộp ngũ cốc có chứa 368grams ngũ cốc"

Giả thuyết thay thế: "Trung bình 1 hộp ngũ cốc không chứa 368grams ngũ cốc"

Xây dựng giả thuyết:
$$H_0: μ = 368$$

Giả thuyết thay thế:

$$H_a: μ \ne 368$$


In [27]:
# Sinh mẫu ngẫu nhiên với cỡ mẫu 25, trung bình 372.5, độ lệch chuẩn 25
sample = np.random.normal(loc = 372.5, scale = 25, size = 25)
sample

array([383.50651851, 405.84658199, 378.03897156, 417.96536765,
       380.80162641, 358.83295594, 364.22207832, 399.9392618 ,
       369.54397375, 413.55745505, 348.20185273, 426.87821886,
       367.16872725, 393.92545486, 353.03731918, 332.28264148,
       402.3700109 , 381.81698587, 366.29016847, 360.92181609,
       374.11791342, 368.84483857, 397.38251772, 349.29624682,
       330.83942406])

In [ ]:
# Xác định thông số:
null_mean = 368

In [29]:
# Kiểm định t:
t_statistic, p_value = stats.ttest_1samp(sample, null_mean)
print(f"p-value: {p_value}")

p-value: 0.09023235688167232


Bài 8: Does an average box of cereal contain more than 368 grams of cereal?  A random sample of 25 boxes showed $\overline{\rm x}$ = 372.5.  The company has specified $\sigma$ to be 15 grams.  Find the p-Value.

Giả thuyết gốc: "Trung bình 1 hộp ngũ cốc có chứa 368grams ngũ cốc"

Giả thuyết thay thế: "Trung bình 1 hộp ngũ cốc chứa nhiều hơn 368grams ngũ cốc"

Xây dựng giả thuyết:
$$H_0: μ = 368$$

Giả thuyết thay thế:

$$H_a: μ > 368$$


In [ ]:
# Sinh mẫu ngẫu nhiên với cỡ mẫu 25, trung bình 372.5, độ lệch chuẩn 25
sample = np.random.normal(loc = 372.5, scale = 25, size = 25)
sample

In [ ]:
# Xác định các thông số:
null_mean=368

In [35]:
# Kiếm định t:
t_statistic, p_value = stats.ttest_1samp(sample, null_mean)
print(f"p-value: {p_value}")

p-value: 8.41480402287198e-07


Bài 9: You’re an analyst for Ford.  You want to find out if the average miles per gallon of Escorts is less than 32 mpg.   Similar models have a standard deviation of 3.8 mpg.  You take a sample of 60 Escorts & compute a sample mean of 30.7 mpg.  What is the value of the observed level of significance (p-Value)?

Giả thuyết gốc: "Số dặm trên một gallon của Escort bằng 32 mpg"

Giả thuyết thay thế: "Số dặm trên một gallon của Escortbé hơn 32 mpg"

Xây dựng giả thuyết:
$$H_0: μ = 32$$

Giả thuyết thay thế:

$$H_a: μ < 32$$


In [36]:
# Sinh mẫu ngẫu nhiên với cỡ mẫu 60, trung bình 30.7, độ lệch chuẩn 3.8
sample = np.random.normal(loc = 30.7, scale = 3.8, size = 60)
sample

array([34.34189091, 28.76583942, 29.76008993, 26.29093658, 29.88696546,
       36.10065896, 29.20999648, 33.12319108, 38.68902852, 34.71811273,
       32.07166142, 23.49697436, 30.28190204, 34.2889242 , 32.02594748,
       34.54602508, 37.55481135, 26.66542148, 36.12402771, 30.89494453,
       30.17856254, 32.61974329, 30.78017107, 26.57303845, 34.16699599,
       27.35341367, 35.15787137, 25.37491953, 29.58921998, 31.35604929,
       29.50692899, 26.23670689, 27.49202025, 36.82216059, 26.4784421 ,
       30.5091082 , 30.7431819 , 27.63765722, 28.30433753, 22.53573342,
       35.37737409, 31.65975016, 31.32320261, 27.31863339, 26.65956848,
       27.17590135, 41.13586519, 32.37472285, 34.47981997, 31.25502533,
       27.61370647, 26.20460343, 35.90752756, 22.93876163, 29.95976884,
       30.09217863, 30.68350727, 30.82875145, 35.64445788, 26.52177446])

In [37]:
# Xác định các thông số:
null_mean = 32

In [38]:
# Kiểm định z:
ztest_Score, p_value= ztest(sample, value = null_mean, alternative='smaller')
print(f"p-value: {p_value}")

p-value: 0.0067118920497757075


Bài 10: Does an average box of cereal contain 368 grams of cereal?  A random sample of 36 boxes had a mean of 372.5 and a standard deviation of 12 grams. Test at the .05 level of significance.

Giả thuyết gốc: "Trung bình 1 hộp ngũ cốc có chứa 368grams ngũ cốc"

Giả thuyết thay thế: "Trung bình 1 hộp ngũ cốc không chứa 368grams ngũ cốc"

Xây dựng giả thuyết:
$$H_0: μ = 368$$

Giả thuyết thay thế:

$$H_a: μ \ne 368$$

Với:
- $α = 0.05$

In [50]:
# Sinh mẫu ngẫu nhiên với cỡ mẫu 36, trung bình 372.5, độ lệch chuẩn 12
sample = np.random.normal(loc = 372.5, scale = 12, size = 36)
sample

array([386.70508127, 391.81169481, 366.3551865 , 362.20068753,
       374.09250077, 361.37912708, 370.58163078, 360.46943591,
       376.67387931, 375.23422437, 391.00970242, 376.59402305,
       377.98906283, 381.48818757, 374.9490224 , 381.08212199,
       368.32753217, 363.7388646 , 379.17565839, 383.85806521,
       384.06404904, 369.8246378 , 388.88663516, 368.84322376,
       377.54197937, 379.41161762, 384.45618643, 373.29624504,
       350.1761247 , 363.3883722 , 380.64788948, 364.76367646,
       366.83311143, 387.1064952 , 359.40179574, 390.60760567])

In [51]:
# Xác định các thông số:
null_mean = 368
alpha = 0.05

In [52]:
# Kiểm định z:
ztest_Score, p_value= ztest(sample, value = null_mean, alternative='smaller')
print("Giá trị của p là:",p_value)
if(p_value <  alpha):
  print("Có bằng chứng để bác bỏ giả thuyết H0")
else:
  print("Chưa có bằng chứng để bác bỏ giả thuyết H0")

Giá trị của p là: 0.9999611462150508
Chưa có bằng chứng để bác bỏ giả thuyết H0


Bài 11: You work for the FTC.  A manufacturer of detergent claims that the mean weight of detergent is 3.25 lb.  You take a random sample of 64 containers.  You calculate the sample average to be 3.238 lb. with a standard deviation of .117 lb.  At the .01 level of significance, is the manufacturer correct?

Giả thuyết gốc: "Trung bình bình chất tẩy rửa nặng 3.25 lb"

Giả thuyết thay thế: "Trung bình bình chất tẩy rửa không nặng 3.25 lb"

Xây dựng giả thuyết:
$$H_0: μ = 3.25$$

Giả thuyết thay thế:

$$H_a: μ \ne 3.25$$

Với:
- $α = 0.01$

In [53]:
# Sinh mẫu ngẫu nhiên với cỡ mẫu 64, trung bình 3.238, độ lệch chuẩn 0.117
sample = np.random.normal(loc = 3.238, scale = 0.117, size = 64)
sample

array([3.21332513, 3.35199017, 3.29759903, 3.21817243, 3.33478143,
       3.08655972, 3.27605125, 3.2297116 , 3.26804486, 3.17282195,
       3.40681596, 3.22202466, 3.1919106 , 3.22837394, 3.39542963,
       3.24368064, 3.06676232, 2.95640852, 3.27284043, 3.22310024,
       3.35818976, 3.07467482, 3.15622198, 3.22707951, 3.34841866,
       3.19264373, 3.42752184, 3.37353838, 3.18042811, 3.20432777,
       3.15913397, 3.32632401, 3.22072209, 3.20276873, 3.22186098,
       3.25007146, 3.43545444, 3.1693462 , 3.20166608, 3.31296995,
       3.17606302, 3.29247258, 3.22899223, 3.13700176, 3.59386913,
       3.18994261, 3.37690731, 3.36199716, 3.22512593, 3.16910679,
       3.12506559, 3.28660841, 3.179616  , 3.26343749, 3.32985194,
       3.1922965 , 3.19474977, 3.23529264, 3.27139319, 3.08014838,
       3.20510147, 3.07214722, 3.32403434, 3.00937835])

In [54]:
# Xác định các thông số:
null_mean = 3.25
alpha = 0.01

In [55]:
# Kiểm định z:
ztest_Score, p_value= ztest(sample, value = null_mean, alternative='smaller')
print("Giá trị của p là:",p_value)
if(p_value <  alpha):
  print("Có bằng chứng để bác bỏ giả thuyết H0")
else:
  print("Chưa có bằng chứng để bác bỏ giả thuyết H0")

Giá trị của p là: 0.1844944903808634
Chưa có bằng chứng để bác bỏ giả thuyết H0


Bài 12: Is the average capacity of batteries less than 140 ampere-hours?  A random sample of 20 batteries had a mean of 138.47 and a standard deviation of 2.66.  Assume a normal distribution. Test at the .05 level of significance.

Giả thuyết gốc: "Dung lượng trung bình của pin là 140 ampere-hours "

Giả thuyết thay thế: "Dung lượng trung bình của pin bé hơn 140 ampere-hours"

Xây dựng giả thuyết:
$$H_0: μ = 140$$

Giả thuyết thay thế:

$$H_a: μ <140$$

Với:
- $α = 0.05$

In [56]:
# Sinh mẫu ngẫu nhiên với cỡ mẫu 20, trung bình 138.47, độ lệch chuẩn 2.66
sample = np.random.normal(loc = 138.47, scale = 2.66, size = 20)
sample

array([141.20465947, 138.01408899, 139.46196023, 140.11093365,
       133.61663887, 141.72587232, 140.17017298, 138.83401197,
       139.03538541, 136.13531795, 138.35519505, 138.8385457 ,
       133.0124984 , 138.2837703 , 136.90211519, 139.25945185,
       141.18968679, 139.24991142, 139.96701995, 139.88584232])

In [57]:
# Xác định các thông số:
null_mean = 140
alpha = 0.05

In [58]:
#Kiểm định t
t_statistic, p_value = stats.ttest_1samp(sample, null_mean)
print("Giá trị p là:", p_value)
if(p_value <  alpha):
  print("Có bằng chứng để bác bỏ giả thuyết H0")
else:
  print("Chưa có bằng chứng để bác bỏ giả thuyết H0")

Giá trị p là: 0.01678415659233666
Có bằng chứng để bác bỏ giả thuyết H0


Bài 13: You’re a marketing analyst for Wal-Mart.  Wal-Mart had teddy bears on sale last week.  The weekly sales of bears sold in 10 stores was: 8  11  0   4   7   8   10   5   8   3. At the .05 level of significance, is there evidence that the average bear sales per store is more than 5?

Giả thuyết gốc: "Doanh số bán háng trung bình của cửa hàng trung bình là 5 con "

Giả thuyết thay thế: "Doanh số bán háng trung bình của cửa hàng trung bình lớn hơn 5 con"

Xây dựng giả thuyết:
$$H_0: μ = 140$$

Giả thuyết thay thế:

$$H_a: μ <140$$

Với:
- $α = 0.05$

In [59]:
# Tạo mẫu:
sample = np.array([11, 0, 4, 7, 8, 10, 5, 8, 3])

In [60]:
# Xác định các thông số:
null_mean = 5
alpha = 0.05

In [64]:
#Kiểm định t
t_statistic, p_value = stats.ttest_1samp(sample, null_mean)
print("Giá trị p là:", p_value)
if(p_value <  alpha):
  print("Có bằng chứng để bác bỏ giả thuyết H0")
else:
  print("Chưa có bằng chứng để bác bỏ giả thuyết H0")

Giá trị p là: 0.3290092357356452
Chưa có bằng chứng để bác bỏ giả thuyết H0
