<a href="https://colab.research.google.com/github/NguyenDuyTan0302/BaiTapNNLT/blob/master/bai_tap_sinh_mau_ngau_nhien.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Sử dụng thư viện Numpy

1. Sinh mẫu ngẫu nhiên bằng hàm arange trong khoảng [-15, 27] với khoảng cách là 0.7 và in kết quả ra màn hình

In [2]:
import numpy as np

In [3]:
np.arange( -15, 27, 0.7)

array([-15. , -14.3, -13.6, -12.9, -12.2, -11.5, -10.8, -10.1,  -9.4,
        -8.7,  -8. ,  -7.3,  -6.6,  -5.9,  -5.2,  -4.5,  -3.8,  -3.1,
        -2.4,  -1.7,  -1. ,  -0.3,   0.4,   1.1,   1.8,   2.5,   3.2,
         3.9,   4.6,   5.3,   6. ,   6.7,   7.4,   8.1,   8.8,   9.5,
        10.2,  10.9,  11.6,  12.3,  13. ,  13.7,  14.4,  15.1,  15.8,
        16.5,  17.2,  17.9,  18.6,  19.3,  20. ,  20.7,  21.4,  22.1,
        22.8,  23.5,  24.2,  24.9,  25.6,  26.3,  27. ])

2. Sinh mẫu ngẫu nhiên theo phân phối chuẩn với mean = 2.7 std = 1.2 và size = 40
In kết quả ra màn hình

In [4]:
np.random.normal(loc = 2.7, scale = 1.2, size = 40)

array([ 1.52225711,  3.86807114,  3.08291748,  0.80485447,  0.57265194,
        1.84532352,  3.54299706,  3.66056808,  1.3008932 ,  2.95763556,
        4.25453091,  3.05359986,  3.98511871,  0.17732634,  2.7885157 ,
        4.26274481,  3.52746145,  0.8579214 ,  4.44638335,  3.35734378,
        2.90688171,  2.20323628,  2.81547338,  2.33760768,  3.02049933,
        0.3805667 ,  3.60995894,  3.565499  ,  3.18929695,  2.94739855,
        1.47869894, -0.85367955,  2.23258196,  2.71697128,  4.08074279,
        2.17661191,  3.36898596,  4.01810058,  3.29127694,  1.48830855])

3. Sinh mẫu ngẫu nhiên từ vector ['Viet Nam', 'Britain', 'France', 'Russia', 'Singapore'] 

với kích thước là 17 theo phân phối chuẩn

In [5]:
np.random.choice(['Viet Nam', 'Britain', 'France', 'Russia', 'Singapore'],size = 17)

array(['Singapore', 'Britain', 'France', 'Viet Nam', 'Britain', 'Russia',
       'Viet Nam', 'Viet Nam', 'France', 'Russia', 'Singapore',
       'Viet Nam', 'Britain', 'Viet Nam', 'France', 'Viet Nam', 'Britain'],
      dtype='<U9')

4. Sinh mẫu ngẫu nhiên ở câu 3 nhưng không theo phân phối chuẩn mà theo 1 vector đặc tả giá trị xác suất do bạn chọn

In [6]:
np.random.choice(['Viet Nam', 'Britain', 'France', 'Russia', 'Singapore'],size = 17,p= [0.2, 0.2, 0.2, 0.2, 0.2])

array(['Russia', 'Singapore', 'Britain', 'Britain', 'Viet Nam', 'Britain',
       'Singapore', 'Russia', 'Viet Nam', 'France', 'Britain',
       'Singapore', 'Viet Nam', 'France', 'Russia', 'Singapore', 'France'],
      dtype='<U9')

Sử dụng thư việc scipy.stats để sinh mẫu ngẫu nhiên

1. Sinh mẫu ngẫu nhiên theo phân phối chuẩn với mean = 12.7, std = 2.6 và size = 30. In kết quả ra màn hình

In [7]:
from scipy import stats

In [9]:
stats.norm.rvs(loc = 12.7, scale = 2.6, size = 30)

array([13.6190418 , 12.16107334,  9.8927868 , 12.38001845, 11.68344632,
       15.9634517 , 15.1625278 , 10.0419922 , 15.73463776, 11.21286029,
       13.04615749, 15.82713407, 10.03564229, 13.11703782,  9.76076425,
        7.65262083, 15.26515432, 12.77339115, 10.56184425,  8.57496542,
       11.65617067, 16.18966614, 13.74641964, 11.73082032, 10.95273907,
       12.97511142,  8.67700598, 16.19649693, 14.00829187, 15.80531157])

2. Hãy sinh một mẫu ngẫu nhiên theo phân phối Poisson

In [10]:
np.random.seed(10)
a= stats.poisson.rvs(mu = 50,size = 100)
a

array([56, 53, 50, 43, 42, 57, 55, 62, 51, 47, 49, 52, 53, 57, 61, 39, 40,
       34, 51, 43, 47, 46, 46, 48, 57, 48, 58, 52, 51, 32, 38, 46, 46, 47,
       60, 60, 52, 52, 46, 46, 51, 49, 47, 46, 52, 37, 56, 52, 47, 46, 54,
       34, 40, 60, 44, 40, 49, 41, 53, 44, 44, 62, 51, 51, 51, 52, 41, 54,
       49, 50, 39, 51, 43, 46, 55, 48, 58, 56, 52, 52, 55, 49, 50, 42, 58,
       49, 40, 39, 37, 51, 53, 47, 57, 48, 48, 58, 50, 70, 59, 43])