<a href="https://colab.research.google.com/github/NguyenDuyTan0302/BaiTapNNLT/blob/master/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Thêm thư viện Numpy

In [16]:
import numpy as np

 1.Tạo ma trận ngấu nhiên A bằng hàm random

In [ ]:
A = np.random.random([7,5])
print("Ma trận A:\n",A)

Ma trận A:
 [[0.02767857 0.50292622 0.22751407 0.16935145 0.2236352 ]
 [0.28515778 0.36676698 0.33345382 0.68833854 0.11796465]
 [0.13562998 0.88244842 0.50075509 0.46568836 0.85805518]
 [0.87134583 0.18493063 0.28547783 0.75278239 0.20070757]
 [0.60979382 0.30786719 0.52969171 0.66006924 0.17963119]
 [0.25943277 0.83016416 0.59808195 0.14887443 0.14182165]
 [0.04662575 0.56097545 0.81663245 0.57700786 0.47290537]]


2.Tạo ma trận không A bằng hàm zeros

In [ ]:
A=np.zeros([6,7])
print("Ma trận không A:\n",A)

Ma trận không A:
 [[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


3.Tạo ma trận vuông A 7x7 bằng hàm random với 2 giá trị hàng và cột được thêm vào bằng nhau bằng 7

In [ ]:
A=np.random.randint(1,20,[7,7])
print("Ma trận A:\n",A)

Ma trận A:
 [[ 2 10 10 14 15  9 16]
 [ 4 19 18  9 12 16  1]
 [ 3  2  9  6 12 16 13]
 [ 3  1 10  4  1  3 11]
 [ 7  2 10 10 13  8  4]
 [12 17 10  9 10  4  9]
 [15  3  3  5 15  5  4]]


4.Đầu tiên tạo ma trận 0 A với kích thước 6x6 
Sau đó tạo giá trị cho đường chéo đơn vị = 15 bằng hàm fill_diagonal

In [ ]:
A = np.zeros([6,6])
np.fill_diagonal(A,val=15)
print("Ma trận chéo A:\n",A)

Ma trận chéo A:
 [[15.  0.  0.  0.  0.  0.]
 [ 0. 15.  0.  0.  0.  0.]
 [ 0.  0. 15.  0.  0.  0.]
 [ 0.  0.  0. 15.  0.  0.]
 [ 0.  0.  0.  0. 15.  0.]
 [ 0.  0.  0.  0.  0. 15.]]


5.Tạo ma trận ngầu nhiên A sau đó biến nó thành ma trận tam giác bằng hàm triu

In [ ]:
A = np.random.randint(1,10,[8,8])
print("Ma trận tam giác trên A:\n",np.triu(A,k=0))

Ma trận tam giác trên A:
 [[3 7 4 5 8 1 7 7]
 [0 4 7 9 2 2 9 9]
 [0 0 4 4 3 9 7 3]
 [0 0 0 9 5 7 7 1]
 [0 0 0 0 7 9 1 5]
 [0 0 0 0 0 3 7 1]
 [0 0 0 0 0 0 9 2]
 [0 0 0 0 0 0 0 4]]


6.Tương tự ở trên nhưng thay triu bằng tril để tạo nên ma trận tam giác dưới

In [ ]:
A = np.random.randint(1,10,[8,8])
print("Ma trận tam giác dưới A:\n",np.tril(A,k=0))

Ma trận tam giác dưới A:
 [[9 0 0 0 0 0 0 0]
 [5 1 0 0 0 0 0 0]
 [5 2 2 0 0 0 0 0]
 [6 3 4 4 0 0 0 0]
 [8 1 7 6 8 0 0 0]
 [6 5 1 5 6 1 0 0]
 [1 2 2 4 6 6 2 0]
 [2 3 3 3 8 8 2 1]]


7.Tạo ma trận đơn vị có số chiều bằng 9 với hàm identity

In [ ]:
print("Ma trận đơn vị I9:\n",np.identity(9))

Ma trận đơn vị I9:
 [[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


8.Tạo 2 ma trận ngẫu nhiên cùng kích thước rồi cộng bằng +

In [ ]:
#cộng hai ma trận
A = np.random.randint(1,10,[6,7])
B = np.random.randint(1,10,[6,7])
print("A+B:\n",A+B)

A+B:
 [[ 8 10 11 12 13  9 15]
 [12 14  6 16  9  4 12]
 [14  9 12 11  7  9 10]
 [ 9  8 13 16 11  2 13]
 [12  9 11  3 13  9  8]
 [ 8 13  8  7 12  9 13]]


Tạo ma trận ngẫu nhiên A rồi nhân vô hướng A với n bằng *

In [ ]:
#Nhân vô hướng
A = np.random.randint(1,5,[5,8])
print(A)
n = int(input("Nhân ma trận với: "))
print("Kết quả của phép nhân vô hướng A với",n,"là\n",A*n)

[[4 3 3 1 4 4 1 3]
 [2 3 2 2 4 2 4 4]
 [2 3 3 3 4 2 4 4]
 [4 1 4 3 4 1 1 4]
 [2 3 4 3 3 1 3 4]]
Nhân ma trận với: 3
Kết quả của phép nhân vô hướng A với 3 là
 [[12  9  9  3 12 12  3  9]
 [ 6  9  6  6 12  6 12 12]
 [ 6  9  9  9 12  6 12 12]
 [12  3 12  9 12  3  3 12]
 [ 6  9 12  9  9  3  9 12]]


Tạo ma trận ngẫu nhiên A rồi chuyển vị

In [ ]:
#Chuyển vị
A = np.random.randint(1,10,[3,7])
print("Ma trận ban đầu:\n",A)
print("Chuyển vị:\n",A.T)

Ma trận ban đầu:
 [[6 4 3 9 2 4 5]
 [6 4 6 2 7 2 1]
 [9 3 8 9 1 1 4]]
Chuyển vị:
 [[6 6 9]
 [4 4 3]
 [3 6 8]
 [9 2 9]
 [2 7 1]
 [4 2 1]
 [5 1 4]]


Tạo ngẫu nhiên 2 ma trận với số cột của A bằng số hàng của B sao đó nhân A với B bằng A.dot(B)

In [ ]:
#Nhân hai ma trận
A = np.random.randint(1,5,[5,7])
print("Ma trận A:\n", A)
B = np.random.randint(1,5,[7,3])
print("Ma trận B:\n", B)
print("Nhân hai ma trận A và B:\n",A.dot(B))

Ma trận A:
 [[1 1 4 4 3 4 3]
 [3 3 2 3 2 1 2]
 [1 3 2 4 3 1 4]
 [2 1 2 1 4 2 1]
 [1 2 4 1 4 1 2]]
Ma trận B:
 [[4 3 3]
 [1 3 4]
 [4 1 4]
 [2 2 3]
 [1 3 1]
 [3 3 4]
 [4 2 1]]
Nhân hai ma trận A và B:
 [[56 45 57]
 [42 39 46]
 [45 42 46]
 [33 33 34]
 [39 34 40]]


Tạo ma trận ngẫu nhiên A rồi tìm nghịch đảo của nó bằng np.linalg.pinv(A)

In [ ]:
#Ma trận nghịch đảo
A = np.random.randint(1,5,[5,5])
A_i = np.linalg.pinv(A)
print("Ma trận ban đầu\n",A)
print("Ma trận nghịch đảo\n",A_i)

9.Tạo ma vecto hàng và vecto cột

In [ ]:
#Vector hàng
A = np.random.randint(1,10,[1,8])
print(A)
A.shape
#Vector cột
A = np.random.randint(1,10,[8,1])
print(A)
A.shape

[[1 6 8 9 7 9 3 5]]
[[3]
 [5]
 [1]
 [7]
 [1]
 [4]
 [4]
 [7]]


(8, 1)

10.Giải hệ phương trình tuyến tính bằng cách tìm ma trận nghịch đảo của A bằng np.linalg.pinv() rồi nhân ma trận nghịch đảo của A cho y bằng np.dot()

In [17]:
import numpy as np
A = np.random.randint(1,10,[3,3])
y = np.random.randint(1,5)
A_i = np.linalg.pinv(A)
x = np.dot(A_i, y)
print(x)

[[-0.48484848 -2.96969697  2.06060606]
 [ 0.18181818  2.36363636 -1.27272727]
 [ 0.36363636  0.72727273 -0.54545455]]
