<a href="https://colab.research.google.com/github/NguyenDuyTan0302/BaiTapNNLT/blob/master/Numpy21_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

*Cú pháp: apply_along_axis(func1d, axis, arr, *args, **kwargs)
*Ý nghĩa:
func1d: Hàm này phải chấp nhận mảng 1 chiều, áp dụng theo hàng hoặc cột của mảng

axis: Xác định trục

arr: Mảng đầu vào

kwargs: Các đối số bổ sung cho func1d

In [ ]:
import numpy as np

A=np.random.randint(0,20,(15,17))
print(A)

[[ 1  6 19  2  9 17 16 15 11  9 12 12  2  5 13 18  6]
 [18  7  0 17 11 13  2 15  6 11  0  8  4  0  2 15 13]
 [ 0 13  1  5 10 11  6  6  1  0  8  5 14  2  6 13  2]
 [ 6  5  1  4  4 18 15 17  1 11  1 19 11 17  8 17 10]
 [ 5 14  6  4  2 15 16 13 19  9  7  8 17 16  3 13 12]
 [ 1  2  0  9  6 13 19 16  8  3  2  9  5  8  9  5  5]
 [14  8 15  6 15 19  9  1  5 16  0 15 11  4 10  8 14]
 [ 4 14  1  1  0 17 11 15 16  9 14 18  7 17  6  2 18]
 [ 8 14  2 11  2 11  5  1 19  6 18 10  5  6 17  6 18]
 [ 6  1 12 16 16  9  3  9  3  2  2 15  4 18  8 19 15]
 [ 0 13  1  7  5  8 12 12 12  3  9 16  9 17  5 18 11]
 [16  5  5 14  9  6  1 15  8  4  8  0 18  2 14 16  9]
 [19 18 11 19 14 14  2 13  0 18 10 13 18  8  8 17  9]
 [ 5  2  2  1  2  0 12  5  3  6  8 15  1  1  1  9  6]
 [15  3 18 19 11 17 13  2 12 12  1  6  7  6  4  0 15]]


In [ ]:
A=np.random.randint(0,20,(15,17))
def tim_max(a):
  return np.max(a)
print(np.apply_along_axis(),1,A))


TypeError: ignored