<a href="https://colab.research.google.com/github/NguyenDuyTan0302/BaiTapNNLT/blob/master/Numpy3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.Trình bày cú pháp của hàm apply_along_axis và giải thích ý nghĩa từng tham số.
*Cú pháp: apply_along_axis(func1d, axis, arr, *args, **kwargs)
*Ý nghĩa:
func1d: Hàm này phải chấp nhận mảng 1 chiều, áp dụng theo hàng hoặc cột của mảng

axis: Xác định trục

arr: Mảng đầu vào

kwargs: Các đối số bổ sung cho func1d

2.Tạo 1 ma trận 15x17 có giá trị ngẫu nhiên bằng random

In [2]:
import numpy as np

A=np.random.randint(0,20,(15,17))
print(A)

[[ 8 14  8  8  4 15 18  1  4 17  7 15  6  6 10  7  8]
 [ 0 15  5 10 18 12 15 19  4 10  1  9  9 13 12  2  5]
 [11  3 15 18  4  7 17  5 19 16  6  2  9  8 14  1 13]
 [12 16  1  1 14  5 11 14 11 16 15 15  0  6  2  8 18]
 [16  5  9  5  1  7  1 10  2 13  3  0  2 10 16 15 14]
 [18 11 12  9  2 10 11 15  1 14 14 14 17 15  1  8  3]
 [18 13 15  2 14 19 14  1 11  6 12  0  9 14  5 16  9]
 [11 10 13 14 11  7 15  3  8 13 18 18  8  9  1  4  1]
 [18 13 10  6  1  4 10 14 18 19  0  5  6 16 18  3  3]
 [18  6 11 17  6 12  2  8  4  8  4 17 13 19  3  9 19]
 [ 1  9  4  2 10  7 18 10 13 14 14 15  4 19 19 19  7]
 [ 9  0  0 17  0  4 12  4  2 17 11 12 19  1 16 19 17]
 [ 2 16 12  1 19  0  4 10 19  6  0  5 17  1  7 15 12]
 [ 6 15 11 15  8 18 10 10  0 18  1  3  8 17 10 17 10]
 [18  4  4 11 17 13  5 18 11  2 10  7 13  9 14 14 12]]


3. Xây dựng hàm tìm giá trị lớn nhất bằng np.max rồi dùng apply_along_axis() để áp dụng cho từng hàng thì ta đưa tham số 1

In [3]:
vector_a =np.array(A)
def tim_gia_tri_lon_nhat(vector_a):
  return np.max(vector_a)
np.apply_along_axis(tim_gia_tri_lon_nhat,1,vector_a)

array([18, 19, 19, 18, 16, 18, 19, 18, 19, 19, 19, 19, 19, 18, 18])

4.Tương tự như câu 3 nhưng thay np.max bằng np.min.
Áp dụng với cột thì dùng 0 trong apply-along_axis()

In [4]:
vector_a =np.array(A)
def tim_gia_tri_nho_nhat(vector_a):
  return np.min(vector_a)
np.apply_along_axis(tim_gia_tri_nho_nhat,0,vector_a)

array([0, 0, 0, 1, 0, 0, 1, 1, 0, 2, 0, 0, 0, 1, 1, 1, 1])

5.Tương tự như câu 4 nhưng thay np.max() bằng np.sum()

In [5]:
vector_a =np.array(A)
def tinh_tong(vector_a):
  return np.sum(vector_a)
np.apply_along_axis(tinh_tong,1,vector_a)

array([156, 159, 168, 165, 129, 175, 178, 164, 164, 176, 185, 160, 146,
       177, 182])

6. Trong hàm tinh_tong_2 ta tạo 1 vòng lặp để cộng các số lẻ

In [6]:
def tinh_tong_2(a):
  sum  = 0
  for i in range(len(a)):
    if (i % 2 != 0):
      sum  = sum +a[i]
  return sum
print("Tổng các phần tử có chỉ số lẻ")
print (np.apply_along_axis(tinh_tong_2, 1, vector_a))

Tổng các phần tử có chỉ số lẻ
[ 83  90  60  81  65  96  71  78  80  96  95  74  54 113  78]
