<a href="https://colab.research.google.com/github/NguyenDuyTan0302/BaiTapNNLT/blob/master/T_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import thư viện cần thiết

In [1]:
import numpy as np
from scipy import stats
import pandas as pd
import math
from statsmodels.stats.weightstats import ttest_ind

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


Xây dựng vấn đề kiếm định:
Điều tra mức độ chi tiêu cho việc giải trí của 25 công nhân của khu công nghiệp A là 2000000 vnđ với độ lệch chuẩn 100000 vnđ. Với mức ý nghĩa 5% ta có thể phát biểu công nhân khu công nghiệp A có thoải mái về tinh thần hay không( tiêu 2200000/tháng cho giải trí)


Xây dựng giả thuyết:
$$H_0: μ = 2.2$$

Giả thuyết thay thế:

$$H_a: μ \ne 2.2$$

Với:
- $α = 0.05$


In [35]:
# Sinh mẫu ngẫu nhiên với cỡ mẫu 25, trung bình 2, độ lệch chuẩn 0.1
sample = np.random.normal(loc = 2, scale = 0.1, size = 25)
sample

array([1.97425891, 2.00122735, 1.90474532, 2.17503303, 1.90028261,
       2.07959856, 1.91209255, 2.0832575 , 1.8715671 , 2.12236716,
       1.8321744 , 1.92601137, 2.190395  , 1.99440675, 1.85644481,
       2.07363241, 1.91990269, 1.82977268, 1.97787911, 2.07886203,
       1.87894142, 2.10928103, 1.99412176, 1.96040194, 1.972532  ])

In [36]:
#Xác định các thông số
null_mean=2.2
alpha=0.05

In [37]:
#Kiểm định t
t_statistic, p_value = stats.ttest_1samp(sample, null_mean)
print("Giá trị p là:", p_value)
if(p_value <  alpha):
  print("Có bằng chứng để bác bỏ giả thuyết H0")
else:
  print("Chưa có bằng chứng để bác bỏ giả thuyết H0")

Giá trị p là: 2.9646594384697086e-10
Có bằng chứng để bác bỏ giả thuyết H0


Xây dựng vấn đề kiếm định: Điều tra mức độ chi tiêu cho việc giải trí của 25 công nhân của khu công nghiệp A là 2000000 vnđ với độ lệch chuẩn 100000 vnđ. Điều tra mức độ chi tiêu cho việc giải trí của 25 công nhân của khu công nghiệp B là 2300000vnđ với độ lệch chuẩn 500000vnđ. Với mức ý nghĩa 5% ta có thể phát biểu công nhân khu công nghiệp A có thoải mái về tinh thần hơn  công nhân ở khu công nghiệp B hay không ? 

Xây dựng giả thuyết:

$$H_0: μ_a= μ_b$$

Giả thuyết thay thế:

$$H_a: μ_a> μ_b$$

Với α=0.05

In [11]:
# Sinh mẫu ngẫu nhiên với cỡ mẫu 25, trung bình 2, độ lệch chuẩn 0.1
sample_A = np.random.normal(loc = 2, scale = 0.1, size = 25)
sample_A

array([1.71332774, 1.85357425, 1.84706203, 2.07572935, 2.11536289,
       2.05518141, 2.01560899, 1.87808874, 1.96253964, 1.96537648,
       2.08262573, 2.10041798, 1.91353613, 1.96687636, 1.95426365,
       2.03913958, 1.98390723, 2.11932   , 1.87211877, 2.03490425,
       2.13214302, 2.05092769, 2.02183144, 1.96825649, 2.1228834 ])

In [12]:
# Sinh mẫu ngẫu nhiên với cỡ mẫu 25, trung bình 2.3, độ lệch chuẩn 0.5
sample_B = np.random.normal(loc = 2.3, scale = 0.5, size = 25)
sample_B

array([2.55450235, 3.3665252 , 2.06970288, 1.9505157 , 2.24767893,
       2.58252862, 1.89324603, 3.21713517, 1.83741507, 1.95575597,
       2.47827028, 2.24235197, 2.51006498, 2.65954203, 2.73123814,
       2.32625402, 2.14375478, 2.02930325, 2.75465137, 2.12593604,
       1.86737072, 2.14682415, 0.90588806, 2.04241192, 1.36220025])

In [9]:
#Xác định các thông số
alpha=0.05

In [13]:
# Tiến hành kiểm định t:
t_statistic, p_value, df = ttest_ind(x1 = sample_A, x2 = sample_B, value = 2 - 2.3, alternative = "larger")
print("Giá trị p là:",p_value)
if p_value < alpha:
    print("Có bằng chứng để bác bỏ giả thuyết H0")
else:
    print("Chưa có bằng chứng để bác bỏ giả thuyết H0")

Giá trị p là: 0.30798268750635704
Chưa có bằng chứng để bác bỏ giả thuyết H0
